### ISSUE TITLE
OAuth sign-in

### ISSUE THREAD

**Issue by BytewaveMLP** [mintyfresh/pone-points#1]
- Discord
- Google
- Twitter?

**Comment by mintyfresh** [comment]
@BytewaveMLP 
I've added Discord and Github to start.

Google makes one just through a bunch of hoops just to get credentials issued and I don't have a Twitter account. :P

**Comment by BytewaveMLP** [comment]
GitHub is a good one, didn't think about that. And yeah, Twitter has a bunch of hoops to jump through to get OAuth creds as well, it's kind of dumb.

I think Discord and GitHub are the two major providers of note, at least for ponydevs.

**Comment by mintyfresh** [comment]
Alright. Adding further OAuth providers is fairly trivial, however, so I'm going to close this ticket until we get some concrete requests.
